### ISSUE TITLE
Classes missing docblocks

### ISSUE THREAD

**Issue by tarlepp** [Dylan-DPC/guzzle-client#12]
File and actual class docblocks are missing.

**Comment by jordyvandomselaar** [comment]
Why would you want file- or class docblocks?

**Comment by Dylan-DPC-zz** [comment]
No plans of adding this now. Will consider it in the future. Thanks

**Comment by tarlepp** [comment]
ok, so no information about method meanings to anyone...

**Comment by jordyvandomselaar** [comment]
The docblocks are above the methods…

**Comment by tarlepp** [comment]
https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md

**Comment by jordyvandomselaar** [comment]
![image](https://user-images.githubusercontent.com/12712484/32138395-3365a530-bc32-11e7-8b0e-baa62576f8e8.png)
