### ISSUE TITLE
missing \ on native functions

### ISSUE THREAD

**Issue by tarlepp** [Dylan-DPC/guzzle-client#13]
see https://github.com/Roave/FunctionFQNReplacer

**Comment by Dylan-DPC-zz** [comment]
No plans of adding this right now. Will consider it in the future. Thanks

**Comment by tarlepp** [comment]
Why not? Performance differences are quite high - although just micro optimizing.

And if you are consider this in future, why to close the issue about it?

**Comment by Dylan-DPC-zz** [comment]
Well i will revisit the issue board later on. Don't worry :stuck_out_tongue:

**Comment by tarlepp** [comment]
ok, so you check all issues over and over again ? personally that doesn't make any sense... why to look closed issues - assuming that those are closed correctly. and in this case this issue isn't...

**Comment by jordyvandomselaar** [comment]
Performance differences being big and micro optimizing  don't go in one sentence. According to the benchmark you posted the difference wasn't all that big, and running a package that tells upfront it will mess up your coding standards isn't that good of an idea. This might be taken under consideration in the future.

**Comment by tarlepp** [comment]
Hmm, and how would this mess up your coding standards?

**Comment by jordyvandomselaar** [comment]
>Please beware that this project uses the internal code generator of nikic/php-parser. This means that it will break your coding style when recreating the sources of your PHP files. This is a known and unresolved issue.

We'll do it manually. Sometime.

**Comment by jordyvandomselaar** [comment]
We'll do it manually. Sometime.

**Comment by tarlepp** [comment]
I'm just wondering how you could remember this after a while... If there isn't open issue about it you basically need to check _all_ issues open/closed ones and see what those contains... and that doen't make any sense...
