### ISSUE TITLE
missing tests

### ISSUE THREAD

**Issue by tarlepp** [Dylan-DPC/guzzle-client#16]
There isn't any tests on this library.  So maybe:
- Add PHPUnit
- Add some tests (functional, integration and unit)

**Comment by Dylan-DPC-zz** [comment]
Aware of this. Didn't have the time yet and focus was on other projects that needed this. Will add some shortly or in case anyone wants to take it up feel free.

**Comment by tarlepp** [comment]
You could also tag this issue with "hacktoberfest"

**Comment by devronhansen** [comment]
i will work on it shortly if that's okay

**Comment by Dylan-DPC-zz** [comment]
Ya sure. The Phpunit & orchestra setup has already been done. So you just have to write the tests. 

Edit: it is not merged yet.

**Comment by devronhansen** [comment]
Ah, i got inspired by another project and planed to use a little lumen server to test against. Is that okay as well?

**Comment by Dylan-DPC-zz** [comment]
Ye that's fine.
