### ISSUE TITLE
Hacktoberfest stuff to do

### ISSUE THREAD

**Issue by Dylan-DPC-zz** [Dylan-DPC/guzzle-client#2]
TODO:

- [x]  Add docblocks to each function
- [x] Format it, removing whitespaces, etc. No need for integration with any third-party service for this
- [x]  Add a readme for it with complete description on installation & usage. Can ask me for further clarification. 

You can submit a PR to master branch.

**Comment by michaeltintiuc** [comment]
In order to help you document the code any contributor would need a bit more insight in your work. Some methods could also be renamed such as `send` and `sendRequest`

**Comment by Dylan-DPC-zz** [comment]
Yes I agree with that. I will try and provide an example in a few days.
