### ISSUE TITLE
Add to Documentation

### ISSUE THREAD

**Issue by jurerick** [Dylan-DPC/guzzle-client#21]
Add to documentation > Installation

Before publishing config, add the below line into service provider `config/app.php:`
Dpc\GuzzleClient\GuzzleClientServiceProvider::class,

**Comment by Dylan-DPC-zz** [comment]
Hi can you send me a PR for this? It is an easy fix :+1:

**Comment by Dylan-DPC-zz** [comment]
The next major release will drop support for 5.4. So there is no need for this.
